export const TURNOVER_DATA = 'turnoverData'
export const ACCOUNT_BOOKS = 'accountBooks'
export const CURRENT_ACCOUNT_BOOK = 'currentAccountBook'
export const ADD_ACCOUNT_BOOK = 'add_accountBook'
export const BILL_DETAIL = 'billDetail'
export const IS_FROM_BILLDETAIL = 'isFromBillDetail'
export const IS_SHOW_BILLDETAIL = 'isShowBillDetail'
export const UPDATE_TURNOVER_ITEM = 'update_turnoverItem'
export const REMOVE_TURNOVER_ITEM = 'remove_turnoverItem'
export const REMOVE_TURNOVER = 'remove_turnover'
export const UNSHIFT_TURNOVER = 'unshift_turnover'
export const PUSH_TURNOVER_ITEM = 'push_turnoverItem'
export const INSERT_TURNOVER = 'insert_turnover'

export const ACCOUNTS = 'accounts'
export const REMOVE_ACCOUNT = 'remove_account'
export const ADD_ACCOUNT = 'add_account'
export const UPDATE_ACCOUNT = 'update_account'

export const CATEGORY = 'category'
export const ADD_CATEGORY = 'add_category'
export const USER_ID = 'userId'
export const TOKEN = 'token'
